spring:
  # data base configuration
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: ${database-password}
    driverClass: com.jc.jdbc.Driver
  # jpa hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8082

eureka:
  username: ${eureka-username}
  password: ${eureka-password}
  client:
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@localhost:8761/eureka/
  fetch-registry: true
  register-with-eureka: true
