spring:
  security:
    user:
      name: ${eureka-username}
      password: ${eureka-password}

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false #this is the server itself so this should not fetch registry
    register-with-eureka: false #and should not register with eureka too
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka
